G = float(input())
N = int(G)

one_hundred = int(N/100)
X = (N - 100*one_hundred)
fifty = int(X/50)
twenty = int((X - 50*fifty)/20)
ten = int(((X - 50*fifty) - 20*twenty)/10)
five = int((((X - 50*fifty) - 20*twenty) - 10*ten)/5)
two = int((X - 50*fifty - 20*twenty - 10*ten - 5*five)/2)
one = int((X - 50*fifty - 20*twenty - 10*ten - 5*five - 2*two))
print("NOTAS:")
print(str(one_hundred)+" nota(s) de R$ 100.00")
print(str(fifty)+" nota(s) de R$ 50.00")
print(str(twenty)+" nota(s) de R$ 20.00")
print(str(ten)+" nota(s) de R$ 10.00")
print(str(five)+" nota(s) de R$ 5.00")
print(str(two)+" nota(s) de R$ 2.00")
print("MOEDAS:")
print(str(one)+" moeda(s) de R$ 1.00")
A = 100*(G - N)
fifty_cents = int(A/50)
twenty_five_cents = int((A - 50*fifty_cents)/25)
ten_cents = int((A - 50*fifty_cents - 25*twenty_five_cents)/10)
five_cents = int((A - 50*fifty_cents - 25*twenty_five_cents - 10*ten_cents)/5)
one_cent = int((A - 50*fifty_cents - 25*twenty_five_cents - 10*ten_cents - 5*five_cents))
print(str(fifty_cents)+" moeda(s) de R$ 0.50")
print(str(twenty_five_cents)+" moeda(s) de R$ 0.25")
print(str(ten_cents)+" moeda(s) de R$ 0.10")
print(str(five_cents)+" moeda(s) de R$ 0.05")
print(str(one_cent)+" moeda(s) de R$ 0.01")
    